name: C/C++ CI

on: [push]

jobs:
  build:
    name: C/C++ CI
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: make Mutex
      run:  make -C ./Mutex
    
    - name: make Semaphore
      run: make -C ./Semaphore
